### ISSUE TITLE
Can't decrypt/extract any firmware files

### ISSUE THREAD

**Issue by AntonKukoba1** [MatrixEditor/hiktools#2]
I have digicap.dav file from DS-2CD2123G0-I firmware and 0 files are extracted there

[IPC_E3_EN_STD_5.5.800_210628.zip](https://github.com/MatrixEditor/hiktools/files/10852301/IPC_E3_EN_STD_5.5.800_210628.zip)

**Comment by MatrixEditor** [comment]
That's possible for newer firmware files as the decryption keys aren't released yet.
